### ISSUE TITLE
勉強会の方針について過去の議論をまとめる。

### ISSUE THREAD

**Issue by ignisan** [sapporocpp/management#12]
勉強会の方針を決めるにあたり、Slackで行われた過去の議論のまとめがないのでログをサルベージしてまとめておく。

**Comment by y-jono** [comment]
過去ログ保存履歴が10000件だったので、BBQ前の議論が消え去ってしまっていました。
OSC最中の議論が残っていたので、貼り付けておきます。

## 6/3 OSC ビラ作成中、次回勉強会の内容を決める際の議論

hotwatermorning [10:41 PM] こんばんはっ。お疲れさまです

hotwatermorning[10:42 PM]次回の勉強会ですが、今までどおりのセミナー形式のものは開催が負担になってきているので、少し形態を変えたいなと考えています。

hotwatermorning[10:43 PM]読書会形式とか、もくもく会形式を取り込む的な。

hotwatermorning[10:45 PM]そんな辺りどうしようかーって漠然と考えている感じ、次回の日程とかはまだ全然白紙です。

hotwatermorning[10:46 PM]やるとしたら7月とかでも可能だと思いますが、他のかたの都合いかがでしょう。（あるいは勉強会の形式についての意見とか）

ignis [10:49 PM] まず発表者確保できない限りはセミナー形式つらいものがあります

hotwatermorning [10:49 PM] はい

ignis [10:49 PM] 自然とやるとしたら読書会とか、全員参加型に。

hotwatermorning [10:49 PM] そうですね。

ignis [10:50 PM] 発表者を探すという方針もあります

ignis[10:50 PM]まずどちらをやりたいか決めてください

hotwatermorning [10:52 PM] 発表者を探す方法はありですが、継続的に発表者を確保できるわけでもないので、何かしら読書会ないし全員参加形式にする必要ありそうです。

hotwatermorning[10:53 PM]それらを開催しつつ発表者を探して、タイミングのいい時にセミナー形式をやるとかが現実的かと思いました。

ignis [10:53 PM] 次回はセミナーはやめておきたいということでOK?
とすると、読書会にすると一度で終わるわけもないので、数回継続することになります。

igni２ヶ月に一度やったくらいでは忘れてしまうので、頻度を上げざるを得ません。

ignis[10:55 PM]少なくてひと月に一回、コンスタントに開催するなら隔週くらいが良いでしょうね。

hotwatermorning [10:55 PM] そうですね。

ignis [10:56 PM] 隔週、負担にならずに開催できますか？よくよく考えてください。

hotwatermorning [10:56 PM] 多分月一くらいになると思います。

hotwatermorning[10:56 PM]隔週でやるのはどうでしょう。例えばそれが習慣になれば可能だと思います。今のところは隔週にするとは決めていませんが。

ignis [10:57 PM] 月１の読書会、他の勉強会のを見ると、一年コースになってるものもあります。結構長期スケジュールです。

ignis[10:57 PM]というか一年で終わらない可能性大きい。

hotwatermorning [10:59 PM] yjonoさんも先程からtypeしてるようなのでどんな風に思うか聞いてみたいです

hotwatermorning[11:01 PM]長期スケジュールですね。実際大阪のEffective C++読書会も、コンスタントにやっていながら結構長かったですし

yjono [11:01 PM] 他の軽めの運用の勉強会を参考にしてみては？
sapporo.beam のようにもくもく会にしてもよいだろうし、hokkaido.pmcasual のようにタイトルだけ決めて、当日ゆるいLT大会にしてもよいだろうし。
読書会は人数が多くいて、担当を持ち回りできれば回数も増やせるとは思いますよ。

hotwatermorning [11:02 PM] ｆｍｆｍ

yjono [11:03 PM] （札幌で一人でもながく続けられた読書会はオム子さんのにしかみたことがないですね）

hotwatermorning [11:03 PM] そうなのですか > 一人でも長く続けられた読書会 (edited)

hotwatermorning[11:04 PM]読書会をやり始めると長期スケジュールにはなりますが、普段から検討しなければならない項目はセミナー形式を続けるよりも少なくなるので、負担は軽くなると考えています

ignis [11:05 PM] 読書会はですね・・・

yjono [11:06 PM] 読書会自体の数は結構多いんですけどね、主催者一人で頑張ってたものって、主催者の環境が変わるとすぐ消えちゃうんですよね・・・

hotwatermorning [11:06 PM] すごいH本読書会・・・

ignis [11:06 PM] 途中から参加しづらいとか、途中で違う本やりたいとか、長期スケジュールになるから色々難しいんですよ

yjono [11:07 PM] ほかにも、実践アジャイルテスティングとかドメイン駆動設計とかRSpec Bookなどなど死屍累々ですね

ignis [11:08 PM] 例えば読書会で興味持ったら、１人で読み進めるんですよ。読み終えるのにひと月かからないですね。すると途中離脱。人が少なくなり自然消滅。

hotwatermorning [11:08 PM] なるほど > 死屍累々

ignis [11:08 PM] Scalaも私が札幌離れたので消えた。主催者の後釜指名してから去ってもね。

yjono [11:09 PM] 逆に、読書会というよりも仲間が集まる集会のような形になってうまくいっているのがオム子さんのやつですね

hotwatermorning [11:09 PM] ｆｍｆｍ

hotwatermorning[11:10 PM]その形だと、内輪の雰囲気になってしまうこととかが懸念されますが、そのあたりってどうでしょう

yjono [11:10 PM] あとは、Hiroさんのやってる数学勉強会とかもそうですね

yjono[11:10 PM]あれもうまいですね

hotwatermorning [11:10 PM] 数学勉強会はすごいですね。よく続いてる

ignis [11:11 PM] あれは主催者不在が逆にうまく行った？

h_hiro_ [11:11 PM] 数学勉強会の場合、問題が次から次へと出てくるので、それで飽きてこないというのがよかったのだと思ってます。（分野自体に飽きてしまうというケースはあるかもしれませんが）

ignis [11:12 PM] あのテーマで新規参入が続いてたのもすごいですね。なんでだろう

h_hiro_ [11:12 PM] 「主催者不在」があまり関係ない内容だった、といえるかもしれません。

usagi [11:12 PM] そもそも読書会やもくもくは（私の考えでは）つまらんから参加しなくなる気がするな。

hotwatermorning [11:12 PM] ｆｍｆｍ

usagi [11:13 PM] 本ははじめから順に読んでいくならすきなものを興味をもって読む層、

usagi[11:13 PM]だから読書会じゃなくて本を紹介する会の方がおすすめだね

hotwatermorning [11:13 PM] なるほど

yjono [11:14 PM] そういうのはあまり見た事ないので、いいかもしれませんね。

usagi [11:14 PM] もくもくは打ち合わせなり手順なり、面白みをきちんと運営でお膳立てして組み立てられないと

usagi[11:14 PM]なんかただあつまって何かしてて、毎回あのひとかこのひとがなんか最後にちょっとなんかしゃべったね会

usagi[11:14 PM]になるので、実は面白く続くというのはそちらのハードルも高いと思う。下手なセミナーの方が楽しめるっていうね。

hotwatermorning [11:15 PM] ｆｍｆｍ

hotwatermorning [11:15 PM] 納得感ある

yjono [11:16 PM] 面白くしたい　のと　運用の負担を軽くしたい　っていうのはなかなか両立がむずかしいですね。（私自身はうまくやれたことがないので）

hotwatermorning [11:16 PM] 難しいですね。

**Comment by y-jono** [comment]
#5 の話も合わせてざっくりまとめると
- セミナー形式はセミナー講師を揃えるのが大変で、セミナー講師の負荷が高い
- 読書会形式は事前準備をセミナー形式より準備の負荷が下がるが、継続性が課題となる
- 読書会は読書会で開催形式をどうするか、会の目的に合わせて深く考慮する。
- もくもく会は負荷が低いが、毎回面白い内容にするにはよく練られたルールが必要
- 読書会についてのignisさんの提案は #5 を見てください。

**Comment by y-jono** [comment]
7/15 の議論では次の勉強会の方針が決まらなかったので、まだチケットを公開しておきます。

**Comment by usagi** [comment]
#9 やもくもくが動き出しているし、ひとまず閉じ。
