### ISSUE TITLE
ConoHa VPSの扱い

### ISSUE THREAD

**Issue by ignisan** [sapporocpp/management#15]
ConoHa VPSを使う案が出ていたが、使うのか使わないのか。
使う場合は何に使うのか。いつまで使うのか。など。

経緯：
タスク管理サービスを選定していた際、VPSに設置したほうがよいサービスもある(Redmine、Gitlabなど)ため、VPSを使用する案があがった。しかし、個人所有のVPSをコミュニティで使用することについて問題提起があり、ConoHa　VPSをコミュニティで運用する案が出た。(※ConoHaは勉強会コミュニティへの支援を行っているため無償利用できる見込みがあった)。ConoHaの利用申請は通ったが、使用方針の議論はMTGで十分になされていない。OSCの準備優先を理由に議論は停止している。

**Comment by usagi** [comment]
@hotwatermorning 活動休止中すみませんが、管理情報を @ignisan かだれかアクティブなコアメンバーへお伝えよろしく。

**Comment by hotwatermorning** [comment]
了解です。

2015年9月30日 3:38 Usagi Ito notifications@github.com:

**Comment by ignisan** [comment]
受け取りました。

**Comment by ignisan** [comment]
#50 MTGでとりあえず使わない方針にしましたので、閉じます
