### ISSUE TITLE
もくもく会

### ISSUE THREAD

**Issue by ignisan** [sapporocpp/management#21]
関連issue #5 
- 開始日時
  - 未定
- 開催頻度
  - 未定(ignis案: 週１もしくは隔週)
- 開催場所
  - 札幌会場
    - 未定(ignis案: スタバなど)
  - オンライン
    - 利用サイトは未定。チャットは必要。
- なにをするか
  - それぞえが各自で好きなこと(C++に関連すること)を行う
  - 何をするか迷う人のために運営側でテーマをいくつか用意しておく。
  - もくもく会中に行ったことをを伝え合う
- 目的(候補)
  - C++の情報交換をするため
  - コミュニティの活動量を増やしてC++に興味を持ってくれる人を増やすため
  - セミナーでの発表者や運営メンバーを増やすため
  - 「新しい発見が生まれたり、新たなコミュニケーションが生まれる」
  - 同時に作業することでよい緊張感が生まれ、自分の作業を能率の高い状態できるようにするため
- 開催を続けるための工夫。モチベを維持するための工夫。
  - 議論中 #5 #23 参照
  - 特に目的意識を持たずに参加する方が多いと予想。そういった方に向けて継続的に取り組めるネタを提供したい。
    - 初心者にはチュートリアルなどをやってもらって質疑応答する
    - 中級者以上には、EC++などを読んでもらう。

**Comment by maraigue** [comment]
8月29日の議事録 → https://github.com/sapporocpp/management/issues/26

**Comment by ignisan** [comment]
集まる人数が多いとは言えないものの継続開催できているようなので閉じる
