### ISSUE TITLE
2015/08/19 MTG

### ISSUE THREAD

**Issue by ignisan** [sapporocpp/management#24]
# 議事録

進行役h_hiro, 議事録ignis
開始: https://pysap.slack.com/archives/sapporocpp/p1439989505000969
終了: https://pysap.slack.com/archives/sapporocpp/p1439999610001160
以下の議事録には終了後の議論も含めている。
# #20 セミナー勉強会
- 17日が都合が良さそう
- 同じ日に重複する勉強会は？
  - まだわからない
  - 早めに告知しよう
- テーマとか、目標とか欲しい(ignis)
  - 参加者が勉強会に参加することで何を得られるのか
  - 運営として何を達成したいか
  - 次回MTGまでに案を出しておく
- 開催場所
  - IL? クリプトン?
  - 設備はIL、立地はクリプトンが良い。
    - ILで協力してくれる社員を探して、見つかったら告知だす？
    - ゲストが来るので立地重視？
  - 開始時間は13時 
## MTGの頻度と非同期での議論
- h_hiro
  - MTGで話す内容は「実務的な話」と「何をするか考える」ということの二つに大きく分けられ、非同期では話しやすい話題と話しにくい話題がある
  - 時間がかかるのは「何をするか考える」で、特に「新しいことを始めようとする」ときで、週１でMTGしないと進まない
  - MTGの頻度を下げることさえできれば負担は減るのかな、というのは感じていて、そのための工夫が何かできればいい
  - 何をするか考えるという議論はある程度時間を取る必要もある
  - 非同期で議論が進めば良いが、新しいアイデアを出したいという段階では、非同期だとなかなかアイデアが出てこないのではないか
  - 個人的にはMTGの開催頻度としては、基本は月1回で、期限がある仕事は随時ここに投稿、勉強会等の直前とその前週は必ず開催、とかがいいのかなと思ってます。
  - 理想的には、実際に会ってブレインストーミングするのが速い
  - 音声チャットも一手
- ignis
  - 試験的に非同期での議論をgithub上で試みたが、コメントが少ない。意見が出なければ進められない
  - 期限を設定していなかったためか、非同期では案が集まらないのか見極める必要がある
- h_hiro: 非同期になると、「考えないと」と思わされるタイミングがない
- ignis: 後回しにしがちになるのは予想出来ていた
- h_hiro: 誰かが作ったたたき台をみんなでブラッシュアップしていくほうがよい
- ignisがたたき台を作って、githubにあげる。コメントがなければ破棄。
- usagi
  - 平日夜中に集まるのがしんどい
  - 非同期でふわふわ進められる方法がいい
## もくもく会
- h_hiro: 自分で何かテーマを考える、いわゆるもくもく会に限らず、「運営側でテーマを設定し、参加者各自が取り組む」というような方式もよいのではないか、という案が出ている。
- ignis: スカイプか何かで音声チャットというのもあり。
- 音声チャットについて
  - skype, google hangout, firefox
  - URLで招待できると良い, firefox, hangoutはURLでも可
## もくもく会とMTG
- もくもく会中に、あるいはもくもく会の前後の時間帯でMTGを行うのはどうか
- セミナー等のリアルイベントでも毎度やってよい
- 10月セミナー勉強会で試してみる
- 営の状況を知ってもらいつつ、運営に協力してくれそうな人も引き込みたい

**Comment by usagi** [comment]
完了したMTGにつきclose
