### ISSUE TITLE
札幌C++勉強会#9 懇親会の企画・検討

### ISSUE THREAD

**Issue by usagi** [sapporocpp/management#29]
- [ ] 会場候補を挙げる
  - このチケットに候補地をぼちぼち挙げておく
- [ ] 会場の決定
- [ ] 一次予約(10名程度で仮予約)
- [ ] 予約人数確定の通知(開催1周間前程度で店に連絡)

**Comment by usagi** [comment]
- 根 駅前店 串焼 おでん: http://www.hotpepper.jp/strJ000957536/

**Comment by usagi** [comment]
前日にも魚介系を遅い時間に食べる事にしたので、成吉思汗に1票かえようかな

usagi [03:21]
そういうわけで、魚介２，成吉思汗２という扱いに。

usagi [03:22]
ミライストカフェから近い魚介なら同じビルのB1Fに安い割にはそこそこ楽しめる寿司バーがある。活一鮮だったかな。

usagi [03:25]
もう２つ魚介系がB1Fにある。まあまあ。

usagi [03:26]
成吉思汗の候補では私は「いただきます。」へ行きたいが、予算的に嫌だって言われそうだな。

usagi [03:27]03:27
http://tabelog.com/hokkaido/A0101/A010103/1036161/party/

食べログ
いただきます。 (すすきの/ジンギスカン)
★★★☆☆3.52 ■ジンギスカンの概念を覆す！当店でしか味わえない、独自品質の北海道産サフォーク！ ■予算(夜):￥2,000～￥2,999

usagi [03:27]
いい肉しか食べる気がなかった私の記憶から欠落していただけで、お高くない肉も食べられるようだ。

**Comment by ignisan** [comment]
予約完了 http://www.yozojin.com/yozojin09/
キャンセルは２日前まで。
17:30-
10-15人と伝えてあるが、できるだけ早めに確定。確定遅れると狭くなる。
