### ISSUE TITLE
C++ Advent Calendar 2015

### ISSUE THREAD

**Issue by usagi** [sapporocpp/management#37]
一昨年までAkiraさん、去年はhotさんに立てて貰ってた C++ Advent Calendar 、今年は hot さんが活動休止しているから、適当に立てるとしようか。

忘れないように備忘録チケットみたいなもの。札幌C++勉強会の名義で立てるわけではないけど、事実上おおくのコアメンバーは今年も参加してくれると思う。

**Comment by ignisan** [comment]
see #47
