### ISSUE TITLE
今後のMTGの方針

### ISSUE THREAD

**Issue by ignisan** [sapporocpp/management#4]
1) 議事録は議論の流れも含めてまとめる
2) 議事録は概略のみまとめ、流れは別途保存

ignis [11:33 PM]
２だろうな

hotwatermorning [11:33 PM]
2でいいと思います。

---
- [x] 会議にかける
- [x] 決定事項のエビデンスを本チケットへ掲載

**Comment by ignisan** [comment]
進行役と議事録担当をどう持ち回るか。

hotwatermorning [11:35 PM]
とりあえず次回まとめ役をくじ引きかなんかで決めて、その人にお願いするようにしてみようと思います

ignis [11:36 PM]
くじ引きじゃなくて、ローテーション組んだ方がいいと思いますが。

hotwatermorning [11:36 PM]
進行役は、チケットが割り振られて、それぞれ進行する担当の人がいる状態になったらお願いする感じがいいかと。

hotwatermorning [11:36 PM]
ローテーションだと、その場にいない人が出た時にどうするかがめんどくさいなっていう

ignis [11:36 PM]
出れない場合は事前に誰かに変わってもらう。

ignis [11:37 PM]
急にいない場合は、仕方ないので誰かが代わりにやる。というかその場合くじ引きでも同じ。

hotwatermorning [11:38 PM]
そこ調整するくらいなら全部くじ引きでいい気がしますが。

ignis [11:38 PM]
次回始まる直前に、次回の担当者をくじ引きで、という意味なら違う (edited)

h_hiro_ [11:39 PM]
あと、進行役と議事録担当は分けていいんじゃないかとも思いました。事情をしっかり把握してない人が進行役に割り当たっても困るでしょうし

hotwatermorning [11:39 PM]
はい。それは思います。 > h_hiro_ (edited)

hotwatermorning [11:40 PM]
議事録は、その場にいる人にお願いしたほうがいいので、MTG始めて人がそろった段階でくじ引きやればいいかなっていう。 (edited)

**Comment by y-jono** [comment]
担当者の割り振り方は議題ごと、MTG終了時に次回の担当者を決めることに決定。このチケットはクローズ。

**Comment by maraigue** [comment]
【ログ要約】
-   ignis:
  -   議題ごとに担当者割り振るメリットは
    -   負担が減る。
    -   issueごとにassignできる。
  -   デメリットは
    -   全体の時間配分がコントロール難しくなる
      -   → 複数人で行う場合、事前に議題ごとの優先度を決めておけばよさそう
    -   都度、担当者を決める手間が増える
-   h_hiro_: その間ずっとMTGに貼り付いてないとならないのが大変。事前に割り当てを決める方式のほうが個人的にはよい
-   yjono: 議事が翌週に持ち越しになった場合、担当者は変更しないほうがスムーズ？
  -   議事録がしっかりしていれば引き継げる。
