### ISSUE TITLE
勉強会 #9 反省会

### ISSUE THREAD

**Issue by usagi** [sapporocpp/management#40]
MTG前でも予め気付いた事があればコメントに書いておきましょう。

**Comment by usagi** [comment]
- ミライストカフェ、日中にスクリーンを設置する場合は日差しの向きを考えないと設置型のプロジェクターとしては輝度がやや不足し、ミエナイ現象が発生する教訓を得た。（大人の放課後はいつも日没後の開催なのでまったく気付いていなかった。）

**Comment by ignisan** [comment]
- オセロAI
  - MSVC対応、考えたくなくても嫌がらずにきちんと準備しよう。
  - AIを作る上で有用な関数をいくつか用意してくと良い。
  - C++に慣れていない人だと時間足りない。
  - 提出までできた人は少なかったが、好感触ではある。もくもく会で続きをやると良いのではないか。
- 全体の進行
  - オセロAI枠に時間をかけざるを得なかったため、公開MTGは断念。猛省すべき。

**Comment by maraigue** [comment]
MTGで出た反省点は https://github.com/sapporocpp/management/issues/41#issuecomment-149928699 になります。

**Comment by usagi** [comment]
↑うまくまとまってる。おつおつ
