### ISSUE TITLE
C++ Advent Calendar 2015 の用意

### ISSUE THREAD

**Issue by usagi** [sapporocpp/management#44]
一昨年まで akira さんが主催していたアドカレ、去年は話を繋いで hot さんが立てた。例年アドカレは立てればC++er各位参加して盛り上がってくれるので、今年も立てるだけ忘れないように備忘録として。

扱い上は札幌C++勉強会が主催するわけではないが、例年から昨年の流れの際に、立てる人の調整など私がしていたところもあるので今年もささやかに動く。

**Comment by ignisan** [comment]
去年の扱いでは、形式上は札幌C++勉強会が実行委員会としてやるけど、実際に動くのは誰でもいいという話になって、たまたまhotさんのリソースがあったからhotさんが立てた。これも備忘録。

**Comment by ignisan** [comment]
C++の会でも話が出たのでそちらで決着した。
初心者向けは @pink_bangbi さんが http://www.adventar.org/calendars/922
普通向けは @ignis_fatuus が http://www.adventar.org/calendars/926
をたてた。
