### ISSUE TITLE
2015/11/7 MTG 

### ISSUE THREAD

**Issue by ignisan** [sapporocpp/management#46]
18:00から
進行: ignis
議事録: @maraigue

**Comment by maraigue** [comment]
# 年末勉強会＆忘年会
- lapisさんに、クリプトン社を使わせていただけるか確認中（ignis） →（後日）12/26大丈夫とのこと
- 正確な日にちは未確定だけど告知出します（ignis）
  - http://sapporocpp.connpass.com/event/22616/
- 発表者を集める問題は依然としてあり

# もくもく会の運用体制と時間帯
- 参加者に希望を取ってみる（h_hiro_）
  - 参加者が少ないって問題はあるのだけどね（ignis）

（その後の意向調査等を受けて）もくもく会は土曜で継続、MTGは平日に移行（次回は11/17火曜日）
