### ISSUE TITLE
今後の勉強会の方針

### ISSUE THREAD

**Issue by ignisan** [sapporocpp/management#5]
今後の勉強会の方針
- セミナー形式を継続？
- 読書会形式？
- なにかその他の形式？
- [x] MTG アサイン
- [ ] 議題の具体化
- [ ] 結果の本チケットへの報告
  - [ ] 必要に応じたサブチケットの発行（XX勉強会開催、など。孫チケットも必要となろうがそれは本チケットではなくサブチケット側での対応とする）

**Comment by usagi** [comment]
保留理由: 先週のMTGまでの経過として #4 完了を待ち落ち着いて考える事になっている

**Comment by maraigue** [comment]
7月8日のMTGでの議論：
-   Sapporo.beamのような、各自が読みたい本を持ってくる（ただしそれは他の参加者に伝える）というのはどうか？（ignisさん）
-   実際にやることや方式までは決まらず。継続議論。

**Comment by maraigue** [comment]
-   ignis: とりあえず開始時に何も考えてないと破綻する。
-   ignis: sapporo.beamの場合はgithubにコメント残していって、やったことを記録できるようにしているらしいです。あと、何か１つの本をやろうということではなく、各々やりたいことをやってるかんじ。ただし、やることは読書会(性格には読書会ではない)の最初で言う。
-   ignis: その他は、前回ここでも話した内容はnikuさんも同意してるようです。つまり、長期でやるので読書会はそもそも破綻しやすい性質がある。

**Comment by maraigue** [comment]
ignis: 読書会（みたいなもの）をやるなら、私はオンラインでの参加ができる方がいいと思います。その上で提案ですが、studyplus http://studyplus.jp みたいなものを使って進めればどうかと。
-   yjono: 全員が同じページを読まなくても、同じ時間にそろっていれば勉強会は成り立つ、ということですか？
-   ignis: はい。同じものでやると、破綻しやすい。
-   hotwatermorning: 勉強用SNSとな。
-   yjono: かなり面白いですね
-   ignis: ただやった内容にコメントできるけど、チャットはない気がする。
-   ignis: チャットないとオンラインだとつらいですね。
-   ignis: 各自がやったログにはできるけど。
-   hotwatermorning: チャットならLingrがvimrc読書会で実績があるようですが。
-   hotwatermorning: 一時期C++部屋も動いてた気がする
-   ignis: sapporo.beamもidobataでチャットして、ログはgithubだから、チャットツールは別に用意すべきなのかもしれない。

**Comment by maraigue** [comment]
hotwatermorning: StudyPlusを使うメリットってなんでしょう。（このSNSの使い方のイメージができてない
-   ignis: 教材の登録ができる(amazonから引っ張ってこれる)、やったとこのページが記録できる。やったことに対してコメントし合える。
-   ignis: 一応コミュニティ機能があるみたいだから、その日にやったことは見やすいと思う。
-   ignis: あと地味に、こいつandroidアプリがあるからどこでもできるといえばできる。

**Comment by maraigue** [comment]
h_hiro_: 休日開催なら1～2ヶ月に1回とかでもいいかなと思います
-   ignis: 読書会なら最低でも隔週は必要だと思いますが。ただし、それぞれ別の本を読むという前提があれば、月イチでもいいのかもしれない。
-   h_hiro_: あ、それぞれ別の本の場合の話でした > 1～2ヶ月に1回
-   ignis: それ出てこなくなると思う。
-   ignis: 継続性が消える。
-   hotwatermorning: 毎週か、長くても隔週でやる必要はあるでしょうね
-   h_hiro_: だとしたら平日ですかねえ
-   yjono: たぶん、読書会というより、C++好きな人が集まる会合になるでしょうね。 > 月１
-   hotwatermorning: 月一回だとすると、読書会っていうよりも、もう少ししっかりした企画のあるものにしないと、あんまり参加者集まらないかなという気がする。
-   h_hiro_: @yjono: 私はそういうイメージがあったので月1を想定してました
-   yjono: @h_hiro 北海道開発オフてきなイメージですか？
-   h_hiro_: @yjono 北海道開発オフを想定していたわけではないですが、それに近いところはあるのかもしれません
-   ignis: studyplusは1つの提案として出しただけで、githubとかがいいという意見があればそれは議論するべきだと思います。そもそも読書会にするともまだ決まってない。

**Comment by maraigue** [comment]
ignis: 月１でやるなら、形式はひと月の間の進捗を発表とかになると思う。
-   hotwatermorning: 全員進捗ダメですで終わる可能性
-   yjono: 月一なら　エクストリームリーディング形式でしょうね その場合、無理やり５回程度で終わらせられる本を選ぶことになる。
-   ignis: @h_hiro_: 月１回しかその本を読まないって状態が私にはなくて、読書会が無いときも読み進めているだろうと考えてる。すると、わざわざ読書会に参加する意味はどこにあるのかと。
  -   h_hiro_ @ignis: 読んだらためにはなるのだろうけど、普段から時間を割いて読んでまではいられない（他に時間を使いたい趣味が多数ある）ので、って本の場合はそうなりますね。私は、以前いくつかの勉強会で本を読み合わせするということをしていましたが、勉強会の中でしか基本的には読んでませんでした。
-   hotwatermorning: エクストリームリーディング分からないので調べてる
-   yjono: http://gihyo.jp/lifestyle/serial/01/study-meeting/0002 この辺が参考になります。たとえば、Effective C++を読むとして、その日に全員が Effective C++を持ってきて、例えば３項目を１０分で読むと決める。
-   ignis: むしろ回数が多い場合にやる形態ではないかという印象
-   yjono: １０分経過後に全員が一言ずつ感想をいう。全員が流し読みしながら、強制的に進むので、回数を抑えられるのがメリット
-   ignis: > 筆者の職場では毎朝30分間，仕事で必要な英語の技術書を5名のチーム内で読み進めています。
-   ignis: というように、少しずつやるならいいと思います。

**Comment by ignisan** [comment]
次回(2015-07-15)でやること
- [ ] #12 でまとめられた内容を各自確認して過去の議論を思い出しておく。
- [ ] 前回のMTGの議事録を確認して議論すべきことを認識する。

最低でも読書会形式か、セミナー形式か、その他かは決める。

**Comment by ignisan** [comment]
議題の進め方
- [ ] セミナー案、その他案がある人がいないか確認
  - [ ] いる場合、その案の利点などを述べてもらう。
    - [ ] 勉強会が優先すべきコトを考慮して、どの案が妥当か判断。
  - [ ] いない場合、読書会に決定する。
- [ ] 決定した案について、より詳細な検討を行う。(おそらく時間切れ？)

終了後
- [ ] 次回のスケジュールを決める。
- [ ] 次回の議題を確認する。
- [ ] 次回の議長担当と記録担当を割り振る

**Comment by ignisan** [comment]
進行役引き継ぎのため補足する。
この議題を終えるためには、簡潔に言えば
- 読書会
- セミナー
- その他

の３択から１つを選べば良い。

そのための典型的な手順は、
1. それぞれの選択肢の特徴や長所短所を明らかにして、
2.  何を重視すべきかを議論し合い、
3.  決定を下す。

という流れになる。

私(ignis)は前回MTGで、
- セミナー形式での発表者確保という問題を示して、
- オンラインも可な読書会という形式を提示し、
- それを実現するための具体的なサービスや参考例などの提示

という上記1を部分的に示した。
次回MTGでは、同様にセミナーを選択する場合について、
- その案の長所や短所などの説明と、
- ignisがあげた発表者確保の問題に対する解決策を提示

をしてもらい、その後、
- 読書会、セミナー以外の案がないか確認し、
- 上記の手順２に移る。

という流れになるはず。

手順２以降については、分岐が多くなるので現段階でのコメントは控える。

**Comment by hotwatermorning** [comment]
# コミュニティ（勉強会）の動機

hot
- 勉強するモチベーション
- C++を使う人同士で盛り上がれる

h_hiro_
- C++が好きな人同士で話す機会ができる
- たまに集中してC++を使う機会ができる（しかも仕事と関係ない形で）

ignis
- 将来を見据えた投資
- C++ユーザが集まってそのうち利益が還元されるという見込み（私以上のC++ユーザが集まる、または育てることを目標としたい）

lapis
- hiroさんと同じ

# やりたいこと

hot
- 読書会
- セミナー

h_hiro_
- もくもく会
- セミナー

ignis
- もくもく会
- セミナー

lapis
- セミナー

# セミナー形式の勉強会について
- 頻度を下げて、年に1, 2回程度、hiroさんignisさんが戻ってくるタイミングで開催する？

```
yjono [11:35 PM] 
全員がやりたいと思う セミナー形式 でやるのがよいのではと思います。あとは課題が解決できたらよいのですが。

yjono [11:37 PM] 
開催頻度を下げて、ignisさんかh_hiro さんが帰ってくるときだけ開催するようにすれば問題は解決しますか？

yjono [11:38 PM]
年に何回もやるからモチベーションがあがらないのかと思いまして。

lapis [11:39 PM] 
セミナー形式はネタ的にも出来ても年に1,2回ぐらいが限界かなーと個人的に思っております

lapis [11:40 PM]
ストックしてあるネタ以外をひり出すのは結構負担

h_hiro_ [11:40 PM] 
一つの手ではあるかもしれません。ただ、最初からそう決められて実施となるとちょっと難しいかも、ってのはあります。帰るタイミングが都合によりずれると勉強会自体が困ったことになるとか
セミナー形式の勉強会を開催する頻度としてはよいのかなというのはあります。

yjono [11:43 PM] 
となると、今日の結論は、年に１回みんなでセミナーやって、もくもくなり読書会なりはSapporo.cppの中のやりたい人だけあつまって主催する形になるのかな (edited)
```

# 読書会／もくもく会形式の勉強会について
- 読書会は破綻することが予測できる(ignis)
- 単なるもくもく会では盛り上がらない（ignis, h_hiro_)
- もくもく会をやるなら、必ずC++についての話題を持ってくるという条件を付けたい(h_hiro_)

```
h_hiro_ [11:47 PM] 
私としては、まずやってみるとよいのでは、と思うまでには至りました。

h_hiro_ [11:47 PM]
一度、もくもく会なり読書会なりを「具体的にどういう手順で開くか」を案として考えてみるとよいかもしれません。どんな目的を打ち出して告知し、どういう進め方にするか。
```

**Comment by ignisan** [comment]
(セミナー開催頻度について) 
ignis 01:49 毎月とは言わないけど、年４回くらいはやらないと、会としてダメだと思う。

**Comment by ignisan** [comment]
ignis 01:24 
なぜか４人がやりたいこと、という視点で話を進められていますが、それはちょっと違うと思います。
考えるべきは、運営する人達がどういうことをやりたいかと、コミュニティにとってどういう形態が最も良いか、です。

**Comment by ignisan** [comment]
usagi 01:32 
もくもく本読むとか輪読（任意参加といってもいわば弱い強制）とか集まってもくもく何かする会はたいへんに希薄な状態でも会として維持コストは低いので、会が消滅する事はないでしょうが
はっきりいうとわたしたぶんそういうのやる会になったら参加しないと思うよ。

**Comment by ignisan** [comment]
usagi 01:37 1つには本は好きな様に読むし、書籍紹介とか論文紹介とかをある対象について解説したり紹介したりは参加して楽しいと思うんだけどね

**Comment by ignisan** [comment]
7/22 MTG 進行役 h_hiro_ 記録担当 ignis
開始: https://pysap.slack.com/archives/sapporocpp/p1437570364000026
- ignis
  - これまでの運営状態(セミナー開催頻度)を維持できるとして、それで十分なのか
  -  今まで以上に、コミュニティを良くするためにはどうするべきかを検討しなきゃならない
  - セミナー開催頻度落とすのってどうなの？ 
- h_hiro_
  - これまでのSapporo.cppが活動内容の割にカツカツの人的リソースで進めてきたのではないか。
- ignis
  - 人的リソースが足りないなら、人を増やす方法を考えるのが正攻法ではないか。
  - 方針が消極的になっている。
  - これまで通りのセミナー頻度(年４回)＋もくもく会(隔週)でもよいのではないか。
    - ライトでオープンな会をできるだけ参加しやすい形で開き、なるべく人を集める。
    - その中で、やったことを軽く教えてもらう。
    - 面白そうなら次回セミナーで少しまとめた形で発表してもらう。
    - つまり、もくもく会をセミナーのスピーカー人材発掘の場としても使う
  - セミナー案は否定していない。他の案を出した上でどうするか決めるべき。
  - 主催者のモチベが落ちているなら、主催交代はひとつの案。主催がモチベ落ちるとコミュニティに影響与えるのでそれは問題。
- h_hiro_
  - モチベーションの高い人が実際の運営を引っ張る、ってのは多分にあり
  - 数学勉強会もそれで存続できているような面がある
- niiyama.sh
  - もくもく会興味あり
  - モチベ問題は人間なので仕方ない。
- usagi
  - 読書会はつまらない
  - 書籍紹介や論文紹介は楽しい
  - もくもく会で工夫があるというのもよい

集まりが悪いため、MTG終了した。
- 各自ログを見てコメントを出しておくことが望ましい。
- 次回MTGは29日(水)？、進行役と議事録係は継続。

**Comment by maraigue** [comment]
開始: https://pysap.slack.com/archives/sapporocpp/p1438146886000163

## 当面の勉強会開催について

まとめ
-   ignisさんが帰省に合わせて勉強会を開く（年内は9月と12月の実施で考えている）。
-   もちろん、札幌在住のメンバーが勉強会を開くのを妨げるものではない。
-   詳細な方式については翌週以降に検討する。

## 議論の詳細
- 議論の発端:
  - 代表のほっとさんはモチベを維持できていない。 
- それぞれの意見
  - hiro: 
    - 今後続けていくには、「モチベーションを牽引する人」が必要
  - ignis:
    - モチベ下がるのは誰でもあるから仕方ない
    - グループで運営してるから誰かが代わりを努めれば済む
    - モチベ下がったままやるのは、コミュニティへの影響良くない
  - hot:
    - 先導して動いていくほどのモチベーションを維持できなくなっている。
    - 誰かにSapporo.cppの運営を引き継いでもらったりしてもらえればありがたい
    - 交代といっても今の運営をそのまま引き継がなくてもよい
    - 札幌を中心に活動するC++のコミュニティならば、札幌にいる誰かに引き継ぎお願いできるといい
    - いままでのメンバー同士での活動の形を残していくなら、札幌っていう地域に縛られないコミュニティになっていってもいい
  - lapis: 
    - 会自体がほっとさんに依存していた部分が大きい
    - 誰かに交代するか休止するかというのは賛成
- そもそも代表が必要か
  -    他の誰かが代表を代わりに行うとした場合、何の仕事があるか
    -   勉強会の開催
      -   勉強会開催の実務については分担を分散できる。代表以外でもでも可能。
    -   外部との窓口
      - この役割があるので、MTGにちゃんと出られる人が望ましい。運営状況を把握している人が必要。
      - 欠席率が1～2割であれば、MTGログを見直すことで「外部からの対応」という面では何とかなる
      - 組織として動く場合、代表いないと面倒くさい 
  - 周りの人に「勉強会しよう！」という気持ちにさせる人、という意味での代表が必要
- それぞれが代表を引き受けられる条件
  - hiro:
    - （仮に札幌に住んでいたとしても）年4回も勉強会を実施できるほどの気力はない。実際には札幌に住んでないので「多くて年1回」になりそう。
    - 仮に代表を要請されても断ります。
  -  ignis:
    - 代表やるのはいいが、札幌にいない人が代表やっていいのかというのが問題
- 休止にするべきか？
  - hot: 
    - 多分いまのSapporo.cppの形としてコミュニティを続けるのは難しくて、一旦休止になるのではないか
  - yjono: 
    - みんなのセミナーやりたいというモチベーションが高まるまで時間おいたらよい
  - hiro:
    - 完全な休止ではないけど（単発で勉強会を開く可能性とかは残すけど）、現状のように常時動くという形態は一旦取りやめるのが良い
  - ignis:
    - 休止にすると、おそらくもう再開は難しい
  - ignis, h_hiroの帰省のタイミングに合わせるにしても一ヶ月以上前から準備が必要。休止状態では難しい。
- 札幌の人以外が代表やることについて
  - ignis:
    - 札幌以外の人が、札幌の勉強会の主催者になることについて、札幌の人はどう思うのか？
    - ignisは札幌離れたので代表に出ることは遠慮している
  - yjono, hot, lapis. h_hiro:
    - 全く異論ない
  - 突発的に札幌の人が勉強会を開きたい場合は？主催者が参加できない状態でも大丈夫なのか？
    - h_hiro: 現地にいなくても、札幌で何が行われるのかを把握できていれば問題ない。
    - ignis: 勉強会やりたければ、勉強会の代表がいなくてもやっていい
- 結論
  - ignisが勉強会を主催していく
  - 誰か札幌の人でモチベある人が現れた場合はまた交代してもよい。

**Comment by lapilapi** [comment]
# 議事録 2015/08/05

## テーマ

* 次回セミナー日程
* もくもく会をどうするか

## 議論

### 次回セミナー日程

* 日程が決まらないと告知と航空券の予約が出来ない
* lapisの空いてる日程は11月,12月
* 12月に懇親会とセミナーを行うのが良い
* 12月に1度開くならば9,10月に1度開いておきたい
* 10月ならば兎さんが横浜わんくまからゲスト（片桐さん）を呼べるかもしれない
* 9月余裕ある人はignis、h_hiro_はこの時期帰る予定はなし
* 10月開催の方向でわんくまの人にも打診できないか

### もくもく会をどうするか

* まずやるのかやらないのか
* もくもく会の内容が先
* もくもく会の内容 ignis案
 - 各自好きなことをやる
 - やったことを簡単に発表してもらう
 - おもしろそうならセミナーでの発表を推薦する
 - 札幌の人は集まってもいい。集まれない人はオンラインも可
* オンラインでやっていくことを念頭に話をすすめていく
* オンラインではモチベーションを保ちにくいのでその問題を検討する
* オンラインではないもくもく会で良いと思っているところ（h_hiro)
 - 「周りに作業している人の雰囲気がある（やる気が出る）」「周りの話が聞こえてくる（場合によっては割り込める）」
* つまり、オンラインだと、他の人が何をやってるのか空気が読めない
* もくもく会のよさは勉強する時間を決めてしまうということ
* 「決まった時間を個人の作業時間にするため」という効果がある
* 「週に1度、C++を勉強する時間をつくろう」というのはアリ
* やるにしても週1は頻度が高い？隔週？
* とりあえず頻度は置いておいて、どのようなもくもく会ならモチベを保ってくれるか、楽しいと思ってくれるかを考える

## まとめ

### 次回セミナー日程

* 12月は懇親会+セミナーをやる予定で
* 10月開催は兎さんからわんくま横浜の人に打診した上で話を進めていく

### もくもく会をどうするか

* モチベーションが保てないので、モチベーションを保てるような内容を議論する
* もくもく会の開催頻度をどうするか議論する

**Comment by lapis** [comment]
# 議事録 2015/08/05

## テーマ
- 次回セミナー日程
- もくもく会をどうするか

## 議論

### 次回セミナー日程
- 日程が決まらないと告知と航空券の予約が出来ない
- lapisの空いてる日程は11月,12月
- 12月に懇親会とセミナーを行うのが良い
- 12月に1度開くならば9,10月に1度開いておきたい
- 10月ならば兎さんが横浜わんくまからゲスト（片桐さん）を呼べるかもしれない
- 9月余裕ある人はignis、h_hiro_はこの時期帰る予定はなし
- 10月開催の方向でわんくまの人にも打診できないか

### もくもく会をどうするか
- まずやるのかやらないのか
- もくもく会の内容が先
- もくもく会の内容 ignis案
  - 各自好きなことをやる
  - やったことを簡単に発表してもらう
  - おもしろそうならセミナーでの発表を推薦する
  - 札幌の人は集まってもいい。集まれない人はオンラインも可
- オンラインでやっていくことを念頭に話をすすめていく
- オンラインではモチベーションを保ちにくいのでその問題を検討する
- オンラインではないもくもく会で良いと思っているところ（h_hiro)
  - 「周りに作業している人の雰囲気がある（やる気が出る）」「周りの話が聞こえてくる（場合によっては割り込める）」
- つまり、オンラインだと、他の人が何をやってるのか空気が読めない
- もくもく会のよさは勉強する時間を決めてしまうということ
- 「決まった時間を個人の作業時間にするため」という効果がある
- 「週に1度、C++を勉強する時間をつくろう」というのはアリ
- やるにしても週1は頻度が高い？隔週？
- とりあえず頻度は置いておいて、どのようなもくもく会ならモチベを保ってくれるか、楽しいと思ってくれるかを考える

## まとめ

### 次回セミナー日程
- 12月は懇親会+セミナーをやる予定で
- 10月開催は兎さんからわんくま横浜の人に打診した上で話を進めていく

### もくもく会をどうするか
- モチベーションが保てないので、モチベーションを保てるような内容を議論する
- もくもく会の開催頻度をどうするか議論する

**Comment by maraigue** [comment]
# 2015-08-11 MTG議事録

## 勉強会の開催：
-   継さんとの連絡は兎さんが取っている。返事待ち。
-   実際に主催するignisさんが、継さんとfacebookで連絡を取り合う手段を設けたい。
  -   チャットだとリアルタイムの通知になってしまい、それは避けたい。→グループを作るのがよいだろうか？
  -   話の内容がSlackとで分離してしまう？→大きな議論はfbでは行わず、連絡手段として使う。必要な情報はSlackにコピペする。
-   札幌の人で話す人はどう集めよう。まだ日程も決まってないので。
  -   それとなく話せる機会があれば話す。Pycon miniとか。

## もくもく会の開催：

### 目的
-   ignis [22:48] **せっかく集まるなら(オンラインででも)、情報交換とか質問とかを気軽にできる環境が欲しいですね。**
-   ignis [22:52] 案が出なさそうなので、少し遠回りかもしれませんが順番に整理して行きますか。
-   ignis [22:53] **まず、もくもく会の目的は何でしょうか？**
-   ignis [22:54] **私は「C++の情報交換をするため」「コミュニティの活動量を増やしてC++に興味を持ってくれる人を増やすため」「セミナーでの発表者や運営メンバーを増やすため」ですかね。**
-   ignis [22:55] **まあ人集め的な側面がありますね。**
-   h_hiro_ [22:56] **私個人としてもくもく会に参加する意義としては、多数の参加者が同時に作業を進めることで、「新しい発見が生まれたり、新たなコミュニケーションが生まれる」「同時に作業することでよい緊張感が生まれ、自分の作業を能率の高い状態できるようにする」ということだと思ってます。**
-   ignis [22:57] とすると、私とhiroさんでは若干目的が違いますね。私は自分の作業の効率化とかはあまり考えてなかった。
-   h_hiro_ [22:58] 二点挙げたうちの後者については、北海道開発オフで個人的に感じたメリットでした。
-   ignis [22:58] 運営としては、もくもく会の目的を決めたほうが良いかと思います。ひとつに絞れというわけではないです。
-   h_hiro_ [22:59] そうですね、どこを主眼におくか決めて、そしてそれをオンラインでどう実現するかですかね
-   ignis [23:00] **hiroさんの目的は、作業結果を見せ合ったりすることで達成できるのではないかと。**
-   h_hiro_ [23:02] それは一つ、というか、最低限入れることになりますね。その目的のためだと。
-   h_hiro_ [23:03] **どちらにせよ（私の言った目的を主眼に置かないにしても）、各個人が実施内容を選ぶという形にするなら、少なくともオンラインで実施するのであれば「実施内容を伝え合う」ということがないと面白くないんじゃないかなと思います** (edited)

### 何を行うか
-   ignis [23:03] でもま、作業結果といっても、C++は難しいんですよね。。短時間で作れるようなお題が少ない。短時間で作るようなものならLL言語の方が適してますから。
-   ignis [23:05] 何かプロジェクトをもってれば、「今日は・・の機能追加を行いました」という話もできるのですが・・。
-   h_hiro_ [23:06] 例えば「今後～～を作ることを想定して、～～について勉強します/コード書きます」とかでいいのかなと
-   ignis [23:06] それができればそれでもいいのですが、
-   ignis [23:07] もくもく会開催しても、勝手にやってください、と放置しただけでは何をすればいいのかわからない人がでるかもしれない。特にC++初心者層は。
-   h_hiro_ [23:07] うーん
-   h_hiro_ [23:09] C++縛りにして、かつ取り組みたいものを自分で考え付かない人へのケアまで考えるとなると、もうもくもく会というよりは「各自のペースで進められる勉強会」って思うのですよね。そういう人たちのためのある種のテーマを用意するわけですし
-   h_hiro_ [23:09] （もしかして、ignisさんが想定しているのはそういう方向性だったりしますでしょうか）
-   ignis [23:10] もくもく会という既存の枠の範囲にしたいとは考えてないです。ベストな形態がもくもく会でないなら、もくもく会じゃない形態で開催してもいいです。
-   ignis [23:11] 便宜上、もくもく会と呼んでるだけです
-   h_hiro_ [23:11] はい

### 題材
-   h_hiro_ [23:16] もし何かテーマありの会として実施するなら、「コードを書きながら学べる教科書/教材」が何かあるといいですかねえ
-   usagi [23:17] もくもくライブラリーつくる会
-   ignis [23:18] 何かを作る会の案は考えたけど、ライブラリを作りたい人ばかりでもないんですよね。集まる人を限定させてしまうかなと。
-   usagi [23:18] まあねえ
-   ignis [23:19] 今って、オンラインで学べるサイトは何が有名なんでしょう？私が覚えた頃はブログもない時代だったから色々サイトがありましたけど。
-   ignis [23:22] 初心者も、初心者以外も参加して楽しい会になればいいんですけど、難しいですね。
-   ignis [23:26] とりあえず、「実施内容を伝え合う」というとこは基本方針に入れて良いかと思います。実施内容を見せてもらえれば、セミナー発表をすすめるべきか判断できますし。
-   ignis [23:27] 見せてもらったことに対して、次回はどんなことをして欲しいかとか、コメントを残すようにするものいいんじゃないですかね。次回参加のモチベになるかもしれない。
-   h_hiro_ [23:29] はい
-   ignis [23:31] Ohotechでやってたような、匿名での投票システムとかはどうかな。
-   h_hiro_ [23:37] 単に導入して参加者にとって意義がすぐに見出せる、ってほどではないかなと思います。「多数投票されようとすることでモチベーションが上がる」ってのだけでなく、「他の人の作業内容を見ることを促す」って意味で実施するならよいと思います。 (edited)
-   h_hiro_ [23:45] ちょっとすぐには次の案が思いつかないところに来た気がしてきた

**Comment by usagi** [comment]
現状、勉強会、もくもく会、動き出していて軌道にも乗りそう。ひとまず当面ほかにあれこれと動く事もないし、チケットをこれ以上間延びさせる理由も無さそうに思うので閉じ。
