### ISSUE TITLE
OSCの収支を帳簿に記録する

### ISSUE THREAD

**Issue by ignisan** [sapporocpp/management#6]
OSCでの収支(デコチョコ費と印刷費)をSapporo.cppの帳簿に記録。
備考欄にデコチョコの発注先・個数をと、
フライヤーの印刷方法(誰がどのように印刷したのか)をメモしておく。

---

MTG:
- [x] 担当者を決定
- [x] 帳簿記録方式を決定
- [x] 目標納期を決定

---

Working:
- [ ] 記録: エビデンスを本チケットへ

**Comment by usagi** [comment]
@hotwatermorning 活動休止と既に長い時間がたっていることから掘り返すコストが高いと判断しクローズ。来年から帳簿すぐ付けましょう、寧ろ計画段階で帳簿は作りましょう。
