### ISSUE TITLE
MTGの事務担当者の決定

### ISSUE THREAD

**Issue by usagi** [sapporocpp/management#9]
- [x] 議長担当決定: 議長担当は議事進行のみを担当する
- [x] 記録担当決定: 記録担当は議題ごとの Issue への状況記録・クローズ・終了後の議事録の記録を行う

※本チケットは担当者を決定するチケット。担当者は毎回選出する。今回は新システムの初動に伴い目進行を明確化するためにあえてチケット化。必要なら次回もチケット化。

**Comment by ignisan** [comment]
2015-07-08の進行役は@ignis、記録担当は@h_hiro_
